"""Database schema constants for VaultDB."""

from __future__ import annotations

SCHEMA_VERSION = 13

KNOWLEDGE_UPDATE_COLUMNS = {
    "title",
    "layer",
    "category",
    "tags",
    "trust",
    "content_raw",
    "content_aaak",
    "content_hash",
    "source",
    "convergence_status",
    "convergence_score",
    "convergence_checked_at",
    "last_verified",
    "freshness",
    "summary",
    "summary_generated_at",
    "scope",
    "sensitivity",
    "owner_agent",
    "allowed_agents",
    "memory_type",
    "expires_at",
    "valid_from",
    "valid_until",
    "supersedes_id",
    "status",
    "archived_at",
    "last_accessed_at",
    "access_count",
    "citation_count",
    "updated_at",
}

MEMORY_CANDIDATE_UPDATE_COLUMNS = {
    "updated_at",
    "title",
    "content",
    "layer",
    "category",
    "tags",
    "trust",
    "source",
    "source_ref",
    "reason",
    "status",
    "privacy_status",
    "duplicate_status",
    "quality_status",
    "gate_payload_json",
    "promoted_knowledge_id",
    "scope",
    "sensitivity",
    "owner_agent",
    "allowed_agents",
    "memory_type",
    "expires_at",
    "valid_from",
    "valid_until",
    "supersedes_id",
}

SKILL_UPDATE_COLUMNS = {
    "name",
    "version",
    "agent_source",
    "category",
    "capabilities",
    "dependencies",
    "trust",
    "content_raw",
    "content_hash",
    "description",
    "updated_at",
    "last_synced",
}

MIGRATIONS = {
    1: "initial_core_tables",
    2: "graph_and_skill_tables",
    3: "convergence_freshness_columns",
    4: "knowledge_summary_columns",
    5: "document_map_semantic_tables",
    6: "memory_candidate_table",
    7: "memory_candidate_quality_status",
    8: "governance_metadata_columns",
    9: "memory_usage_and_archive_columns",
    10: "memory_feedback_events",
    11: "temporal_validity_columns",
    12: "task_ledger_tables",
    13: "task_ledger_priority_and_skill_revisions",
}
